export default {
  DISPOSE_SERVER_ERROR: 'DISPOSE_SERVER_ERROR',
  SERVER_ERROR: 'SERVER_ERROR',

  MAP_LOAD_REALT_SALE: 'MAP_LOAD_REALT_SALE',
  MAP_LOAD_REALT_SALE_SUCCESS: 'MAP_LOAD_REALT_SALE_SUCCESS',
  MAP_LOAD_REALT_SALE_FAIL: 'MAP_LOAD_REALT_SALE_FAIL',

  MAP_UPDATE_BOUNDS: 'MAP_UPDATE_BOUNDS',
  MAP_SET_POINTS: 'MAP_SET_POINTS',

  SET_FILTER_STATE: 'SET_FILTER_STATE',

  FILTER_FLATS: 'FILTER_FLATS',
  FILTER_FLATS_SUCCESS: 'FILTER_FLATS_SUCCESS',
  FILTER_FLATS_FAIL: 'FILTER_FLATS_FAIL',

  FILTER_RENTS: 'FILTER_RENTS',
  FILTER_RENTS_SUCCESS: 'FILTER_RENTS_SUCCESS',
  FILTER_RENTS_FAIL: 'FILTER_RENTS_FAIL',

  MAP_DETAILS: 'MAP_DETAILS',

  DETAIL_LOAD_SALE: 'DETAIL_LOAD_SALE',
  DETAIL_LOAD_SALE_SUCCESS: 'DETAIL_LOAD_SALE_SUCCESS',
  DETAIL_LOAD_SALE_FAIL: 'DETAIL_LOAD_SALE_FAIL',

  DETAIL_LOAD_RENT: 'DETAIL_LOAD_RENT',
  DETAIL_LOAD_RENT_SUCCESS: 'DETAIL_LOAD_RENT_SUCCESS',
  DETAIL_LOAD_RENT_FAIL: 'DETAIL_LOAD_RENT_FAIL',

  DETAIL_CLOSE: 'DETAIL_CLOSE',
}
