export default {
  DISPOSE_SERVER_ERROR: 'DISPOSE_SERVER_ERROR',
  SERVER_ERROR: 'SERVER_ERROR',

  MAP_LOAD_REALT_SALE: 'MAP_LOAD_REALT_SALE',
  MAP_LOAD_REALT_SALE_SUCCESS: 'MAP_LOAD_REALT_SALE_SUCCESS',
  MAP_LOAD_REALT_SALE_FAIL: 'MAP_LOAD_REALT_SALE_FAIL',

  MAP_UPDATE_BOUNDS: 'MAP_UPDATE_BOUNDS',
  MAP_SET_POINTS: 'MAP_SET_POINTS',

  SET_FILTER_STATE: 'SET_FILTER_STATE',

  FILTER_FLATS: 'FILTER_FLATS',
  FILTER_FLATS_SUCCESS: 'FILTER_FLATS_SUCCESS',
  FILTER_FLATS_FAIL: 'FILTER_FLATS_FAIL',
}